pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Checkout the 'main' branch explicitly
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: 'https://github.com/GitGuru4DevOps-Venkatesh/service-website.git']]])
            }
        }
        stage('Update Website') {
            steps {
                // Pull the latest changes from the repository
                sh 'git pull origin main'

                // Restart the Docker container to apply the changes
                script {
                    def containerId = sh(script: 'docker ps -q --filter "name=service-website"', returnStdout: true).trim()
                    if (containerId) {
                        sh "docker restart $containerId"
                    }
                }
            }
        }
    }
}
