pipeline {
  agent any

  triggers {
    // Manual trigger instead of automatic triggering
    manual {}
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build & Deploy') {
      steps {
        script """
        if [ "$(git diff --cached --name-only)" != "" ]; then
          echo "Changes detected! Building Docker image..."
          docker.image('service-website').build()
        else
          echo "No code changes detected. Skipping build."
        fi
        """

        // Assuming the container runs on port 80 and uses the current directory for content
        sh 'docker run -d -p 80:80 . service-website'
      }
    }
  }
}
